### ISSUE TITLE
[BUG] cpu allways 100% 10s computer is shutdown

### ISSUE THREAD

**Issue by powerful001** [Alkl58/NotEnoughAV1Encodes#155]
**Describe the bug**
run it cpu allways 100% 10s computer is shutdown 
![Snipaste_2024-01-27_12-48-05](https://github.com/Alkl58/NotEnoughAV1Encodes/assets/66508520/9b384d42-3167-4456-be0f-020943933fe9)
 restarting the program run is exit

**Desktop (please complete the following information):**
 - OS: [e.g. Win10 20H1]
 - NEAV1E Version: [e.g. v2.1.5]

**Comment by Alkl58** [comment]
I am not sure I understand your issue entirely. You can use [DeepL](https://www.deepl.com/translator) to translate better.

From what I understand, you have 100% CPU usage when encoding. That is expected and we want the highest possible CPU usage for the fastest possible encode.

NEAV1E can shutdown your PC, when the option in the settings is enabled for it. It shouldn't shutdown your system after 10s.
My best guess is that your system get's unstable (maybe thermal issue) because of the high load resulting in it shutting down.

**Comment by powerful001** [comment]
No problems with the new version
