### ISSUE TITLE
Shuts down PC after encoding is finished. Toggle is set to off.

### ISSUE THREAD

**Issue by gimix311** [Alkl58/NotEnoughAV1Encodes#30]
The shutdown after encode toggle is set to off, but it shuts down my PC regardless.

**Comment by Alkl58** [comment]
This issue has been fixed in 58a1ded27c431ebd0b1227305b08172cad146d2c

You can download it here: [click](https://ci.appveyor.com/project/Alkl/notenoughav1encodes/branch/master/artifacts) (you only need to extract the main .exe file and replace the current installed one with this)

Mangy Greetings and sorry for the inconvenience

**Comment by gimix311** [comment]
Works like it should now. Thanks for the quick fix!
