### ISSUE TITLE
[SUGGESTION] Cross-platform command-line AV1 / VP9 / HEVC / H264 / VVC encoding framework with per scene quality encoding

### ISSUE THREAD

**Issue by forart** [Alkl58/NotEnoughAV1Encodes#33]
I found this interesting framework that aims to:

_Spliting video by scenes for parallel encoding because AV1 encoders are currently not good at multithreading, encoding is limited to single or couple of threads at the same time._

- [PySceneDetect](https://pyscenedetect.readthedocs.io/en/latest/) used for spliting video by scenes and running multiple encoders.
- Fastest way to encode AV1 without losing quality, as fast as many CPU cores you have :).
- Target Quality mode. Targeting end result reference visual quality. VMAF used as substructure
- Resuming encoding without loss of encoded progress.
- Simple and clean console look.
- Automatic detection of the number of workers the host can handle.
- Building encoding queue with bigger files first, minimizing waiting for the last scene to encode.
- Both video and audio transcoding with FFmpeg.
- Logging of progress of all encoders.

Github: https://github.com/master-of-zen/Av1an

EDIT: dunno if can help/inspire, but I just found a GUI for it -> https://github.com/natis1/qencoder

Hope that helps/inspires !

**Comment by Alkl58** [comment]
I am not sure what you want me to do.

NEAV1E technically can't be cross platform, also using Av1an as backend for NEAV1E is not possible (lack of knowledge, no reason in doing so, Python, ...)

#### Here is what NEAV1E can do:
✓ Spliting video by scenes for parallel encoding because AV1 encoders are currently not good at multithreading, encoding is limited to single or couple of threads at the same time.
✓ PySceneDetect used for spliting video by scenes and running multiple encoders.
✓ Fastest way to encode AV1 without losing quality, as fast as many CPU cores you have :).
✓ Resuming encoding without loss of encoded progress.
✓ Automatic detection of the number of workers the host can handle.
✓ Both video and audio transcoding with FFmpeg.
✓ Logging of progress of all encoders.

#### What NEAV1E can't do:
X Target Quality mode. Targeting end result reference visual quality. VMAF used as substructure
X Simple and clean console look.
X Building encoding queue with bigger files first, minimizing waiting for the last scene to encode.

**Comment by forart** [comment]
Well, sorry I didn't understand that NEAV1E is the Av1an "counterpart"....

I'll post different suggestions then, please close this.

**Comment by natis1** [comment]
@forart qencoder developer here.

* qencoder is NOT a gui of av1an
* av1an is NOT designed to be a general purpose library for video encoding. It's designed to be a console program.
* what did you even open this github issue for?

**Comment by forart** [comment]
@natis1 Thanks for your clarifications, my "issues" (= suggestions) aims to create/promote collaborations between open projects.

**Comment by Alkl58** [comment]
Well Av1an, qencoder, FastFlix and NEAV1E are on the same (AV1) Discord Server. 
We help each other out for encoding related stuff.

**Comment by forart** [comment]
> Well Av1an, qencoder, FastFlix and NEAV1E are on the same (AV1) Discord Server.
> We help each other out for encoding related stuff.
>
Didn't know, sorry.

**Comment by Alkl58** [comment]
No need to feel sorry ^^
From time to time there is a little tension between a few of us, so we expect such comments being troll posts or similar.
If it is okay for you I will close this issue.
I wish you a nice day and merry christmas!
