### ISSUE TITLE
[Enhancement] Audio bitrate setting clarification

### ISSUE THREAD

**Issue by Palulukas** [Alkl58/NotEnoughAV1Encodes#42]
Hello Aiki58, 

thank you for your great work on this program. It really helps me in reducing the file size of my library. :-)
I have a improvement suggestion for you: The audio bitrate is as of my understanding set **per channel**. For the absolute beginner, it is difficult to understand that for example aac 160kbit/s is the mono bitrate and ends up being 320kbit/s in stereo. 

A little addition in your naming convention or a mouse-over hint with "per channel" would be very helpful for these guys. 

Thank you and kind regards

Lukas

**Comment by Alkl58** [comment]
The audio bitrate is the total bitrate allocated for all channels.

There isn't a "per channel" bitrate option: https://trac.ffmpeg.org/ticket/4078

Either you understood something wrong, or there is a bug in NEAV1E which results in wrong set Bitrate.

**Comment by Palulukas** [comment]
Hello Alkl58, 

I guess that I understood something wrong there... That's a bummer.  😢 
Then I have to see if the smplayer, which I use to check the original settings, calculates per channel or if my animes all have only 128 kbit/s audio quality.... 

Thank you!

**Comment by jderickson** [comment]
For what it's worth @Palulukas I'm pretty sure all encoders and and players display the total bitrate for the stream, regardless of number of audio channels. I've never encountered a player or media inspector that indicated bitrate-per-channel by default without specifying immediately that it was per-channel (e.g. 64/ch or something like "2x64").

I'm not sure what codec you are using, but since you are interested in AV1 I'm assuming you prefer the most efficient available. At 128 Kbps (64 Kbps/channel) Opus and xHE-AAC/USAC (via Exhale encoder) are considered transparent for most kinds of general sources. The key here for xHE-AAC/USAC is that you use the Exhale encoder as it seems to be the highest-quality, most efficient encoder available and is open-source. A lot of people are concluding that it's even superior to Opus at/below 96 kbps.

So I wouldn't worry too much if you're seeing a lot of 128 Kbps streams in your collection (unless they were encoded with much older versions of AAC encoders).

**Comment by Alkl58** [comment]
I will close this issue for now; feel free to reopen it if there is still an issue.

Many Greetings
