### ISSUE TITLE
Can't get video information with latest appveyor exe

### ISSUE THREAD

**Issue by thx4ever** [Alkl58/NotEnoughAV1Encodes#49]
Hi, i'm trying to use latest added features on the WIP version from appveyor and this happens when i try to open a mkv file

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	NotEnoughAV1Encodes.exe
  Problem Signature 02:	1.3.294.0
  Problem Signature 03:	bae26830
  Problem Signature 04:	NotEnoughAV1Encodes
  Problem Signature 05:	1.3.294.0
  Problem Signature 06:	bae26830
  Problem Signature 07:	32
  Problem Signature 08:	6
  Problem Signature 09:	System.DllNotFoundException
  OS Version:	6.1.7601.2.1.0.272.7
  Locale ID:	1046
  Additional Information 1:	b726
  Additional Information 2:	b72633a7658729af14e8eabbae680de7
  Additional Information 3:	e350
  Additional Information 4:	e350084a3a7c0842ccba9879dae0e188

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

I have installed .net framework 4.8 and the one required by this program, also i installed microsoft runtime files

Regards

**Comment by Alkl58** [comment]
Yes, NEAV1E started using MediaInfo.dll since recently, which is not included in the AppVeyor Builds.

To proceed, download [MediaInfo from here](https://mediaarea.net/download/binary/libmediainfo0/21.03/MediaInfo_DLL_21.03_Windows_x64_WithoutInstaller.zip), extract the zip and only copy/move the `MediaInfo.dll` to the directory of NEAV1E.

Many Greetings

**Comment by thx4ever** [comment]
Thanks, problem solved

Regards
