### ISSUE TITLE
[AOMENC] Encoding speed decreases over time - low CPU useage

### ISSUE THREAD

**Issue by ferdinandwinters** [Alkl58/NotEnoughAV1Encodes#50]
Remember those sketchy download sites from years ago that used to slow the download speed over time for files and eventually you couldn't complete the download before the heat death of the universe? That's what's happening.

When I did my first encode it was running at around 20-24 FPS, it slowly crept down to 10, and then 5, and then 1, and I canceled it when it hit 0.24 FPS.

I don't know how else to describe it.

As the FPS goes down so does the CPU usage with it.

If you would like a log or something please respond with how I can get that for you.

**Comment by Alkl58** [comment]
Thats a normal "phenomenon".

I think you might not understand how the program works.

1. Split the Video into Chunks (by scene or n-seconds)
2. Encode the Video Chunks with n-amount of workers
3. After Encoding is finished, merge all encoded chunks back together

Now what happened: During ~90-98% of the time, all workers (aomenc instances) had a chunk to encode, which results in high encoding speed. After that, if the amount of chunks left decreases under the amount of workers, it will slow down.

In theory one worker can be encoding on one chunk multiple times longer than other workers on different chunks. Resulting in other workers terminating their work before the difficult chunk finishes.
The phenomenon is, that there might be only 1-2 workers instead of for example 8 workers in the end, meaning it slows down drastically.

**Comment by ferdinandwinters** [comment]
Ah I see, that makes sense. Thank you for explaining.

So the only thing is to wait for that one chunk to be done or for the entire encode to get through the 'rough patch' and then it will get going again?

**Comment by Alkl58** [comment]
No, it will wait for that one chunk at the end to finish.
The only issue which others have encountered is that the instance won't terminate properly, thus being stuck. 
(If you watch in Task Manager and see it using for example 8MB of RAM and without CPU Utilization, then it's a stuck process)

**Comment by ferdinandwinters** [comment]
Ah right, I see that now.

Swapped to the SVT and it managed to keep going but went from 10FPS to 1.5, so that's alright I guess.

Can the stall issue be resolved by stopping and starting it again?

**Comment by dffvb** [comment]
I am having a similar problem. I started encoding a 180 minutes mpeg2 mkv. It runs since 40 minutes - 20k frame sof 250k frames done. In the beginning it had 20 fps/s now it has gone down to 10 fps/s thus remaining time increasing. I am running it on a i5-8400 - with tower cooler, all fans are running, temps are okay. Any idea? 

Apart from that: Thanks for the work!

**Comment by Alkl58** [comment]
Ok, perhaps I have to explain it a bit differently.

The ETA and FPS are really inaccurate in the beginning. When using encoders like aomenc, rav1e and svt-av1, then the amount of frames "encoded" are actually the amount of frames "buffered" / piped to the external encoder.

The buffer has ~20-30 frames (I am not exactly  sure what the exact number is), meaning that in the beginning it "buffers" a lot of frames, depending on the worker count.

If you have like 6 workers, it will result in 6 x ~25 frames => ~150 being "buffered" instantly. This leads to the side effect that the ETA calculation is not accurate in the beginning.

The decreasing FPS however has many different factors. 
FPS will decrease, if there are chunks with more complicated to encode scenes.
FPS will decrease, if the chunk count is less than the worker count. (NEAV1E will only be "effecient", if all workers are working at all times).
FPS will decrease, if you do 2-Pass encoding and it hitting the second pass.

When the encode is nearly finished, the ETA will rise and FPS will drop pretty noticable, because there might only be one / two workers out of six workers left, who do something.

**Comment by dffvb** [comment]
Thank you :-)

**Comment by Alkl58** [comment]
As the ETA calculation is not accurate enough, it has been removed in 9a14e09f30799379d7caaa2ed2b6880ac2fdb548.

In the end, there is no viable / accurate and easy way especially as there are too many variables.
