### ISSUE TITLE
[Feature] Auto update, metadata (txt), aspect ratio needs to be same fix of DVD.

### ISSUE THREAD

**Issue by MartinEesmaa** [Alkl58/NotEnoughAV1Encodes#60]
Hello!
I would like request, that I wanna get automatically updates builds, before I start encoding video.
Metadata need for input .txt will be displayed the same as original metadata video to same metadata from original encoded AV1/VP9 video.

My DVD is 16:9 original. For AV1 video codec with NEAV1E program, it makes me wrong aspect ratio of 4:3, 5:4 or 3:2 after encoding to AV1.

Add feature update to unstable version? What do you think?

- Martin Eesmaa

**Comment by Alkl58** [comment]
Fixed in Release https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.0.5

I only reproduced this behavior when using the external encoders, like aomenc.

The new behavior is that it will read the display aspect ratio with MediaInfo and then add the apsect ratio back in the muxing stage.

Many Greetings
