### ISSUE TITLE
[Feature] More my updates request.

### ISSUE THREAD

**Issue by MartinEesmaa** [Alkl58/NotEnoughAV1Encodes#62]
Hello, @Alkl58! I forgot these my request updates.

1. Arabic Language missing in Audio tab
2. Credits needs to be who will be thanked to v2 update requesters, developers and creator to make version 2.
3. Animation colour theme acent, custom colours acent theme and rainbow acent theme.
4. Yadif must replaced by QTGMC. QTGMC must be set always Placebo. No double frame rates from 25 to 50 FPS.
5. Override Worker Count needs to be fixed, because it switched off after closing settings.
6. mkvtoolnix GUI must be manually copy automatically from mkvtoolnix directory to NEAV1E app: %AppData%\NotEnoughAV1Encodes\Apps\mkvtoolnix or new build auto update mkvtoolnix?

I will bring some later, if I catch...

- Martin Eesmaa

**Comment by Alkl58** [comment]
>    3. Animation colour theme acent, custom colours acent theme and rainbow acent theme.

Theming is done with https://github.com/MahApps/MahApps.Metro
I won't do custom themes, as it's handled by MahApps Metro.

>    4. Yadif must replaced by QTGMC. QTGMC must be set always Placebo

QTGMC seems to be an Avisynth filter. NEAV1E does not support Avisynth, nor Vapoursynth. Only filters which are inside FFmpeg can be currently implemented.

>    5.  Override Worker Count needs to be fixed, because it switched off after closing settings.

Fixed in the new .NET Core Version of NEAV1E.

>    6. mkvtoolnix GUI must be manually copy automatically from mkvtoolnix directory to NEAV1E app: %AppData%\NotEnoughAV1Encodes\Apps\mkvtoolnix or new build auto update mkvtoolnix?

Sadly, there is no "direct" download for MKVToolnix. I have implemented a way to see the current version and the update version. However updating it has to be done by the user.
