### ISSUE TITLE
[Clarification] Splitting Settings

### ISSUE THREAD

**Issue by slate0** [Alkl58/NotEnoughAV1Encodes#67]
**Is your feature request related to a problem? Please describe.**
I would like to make sure I understand the new-ish splitting options, including how to completely disable splitting, and what "Skip Reencode" does.

**Describe the solution you'd like**
1) My guess is that setting Splitting to "Equal Chunking" and setting Chunk-Length to 0 turns off splitting, but it would be nice if this were an explicit option.  
2) I have never heard of a separate Reencode step with splitting, which is being controlled by the "Skip Reencode" option.  Is there reference information about this?  What setting would match the behavior from before the setting was introduced?

**Comment by Alkl58** [comment]
Haven't replied here, because I figured you would be the person on Discord.

However, here the answer for others:

Reencoding, which others already stated, is only meant for chunking purposes, with greatly reducing the probability of loosing frames in that process.

There is no "way" to skip the entire chunking process, for this, you have to set the Chunking Length higher than the length of the video.

The .NET Core version, which also works under Linux with Wine, can in theory skip the entire chunking process, by setting the setting to encode the queue in parallel instead of the video itself.
