### ISSUE TITLE
[BUG] Chunk encode stopped before the actual deadline (NEAV1E 2.0)

### ISSUE THREAD

**Issue by vertexgamer** [Alkl58/NotEnoughAV1Encodes#71]
for some reason, neav1e 2.0 finished encoding a chunk before it was actually finished. I have accidentally filled my ram during the encode, but every other worker is doing fine 
i'm not sure if this log is useful, but i will upload it anyway
[000007_stats.log](https://github.com/Alkl58/NotEnoughAV1Encodes/files/7659793/000007_stats.log)

**Comment by Alkl58** [comment]
The encoder most likely crashed because of it not having enough ram.

The log file you provided is the file used for two pass encoding (two pass stats), thus has nothing to do with "logging".

In theory all you need to do is to delete `000007_stats.log` and `000007_finished.log. After this it should be possible to re-start the encode and it should resume the encoding process.

Else the more interesting log is the file created in the output directory.
