### ISSUE TITLE
Several features request[Feature]

### ISSUE THREAD

**Issue by neoOpus** [Alkl58/NotEnoughAV1Encodes#88]
Hello,

I've been using this since a moment, and I am very excited about how the new version performs, it is pretty stable so far and the encoding speed has been improved a lot...

I would like to list few features that can bring more user-friendliness and may help to get the best out of AV1 encoding without hindering the day to day responsiveness of the system (mainly for those who use it on their principal machine)

1- Please make some improvement on the Queue to allow selecting and deleting jobs, auto-delete jobs on finish (or just flagging them as finished with auto-saving of the status)... sometimes there is need to restart the machine or stop the job and resume it later, and it is hard to manage right now the tasks and require some manual checking and one by one removal... export/import of the list also can be a great addition.
 
2- Auto-detect when the machine is idle (no user-interaction) to increase the encoding priority or just resume the encoding if it has been paused (I often pause it myself since it make my machine slow but forget to resume the encoding while I am sleeping)...

**Comment by Mfarooq360** [comment]
In Pre-v2.0, you could restart your computer and be able to resume the encode from close to where it was left off, but I think the way it works now is by making a temp folder with a random name instead of the name of the video when adding to and starting queue which makes it start all over again after a restart or a re-add.

**Comment by Palulukas** [comment]
I agree with the issue starter that it would be nice to select multiple items or all items at once in the queue to either delete them or edit them (at once), for example changing the language, subtitles or audio settings.

**Comment by Alkl58** [comment]
> In Pre-v2.0, you could restart your computer and be able to resume the encode from close to where it was left off, but I think the way it works now is by making a temp folder with a random name instead of the name of the video when adding to and starting queue which makes it start all over again after a restart or a re-add.

The random name is saved as unique identifier in each project json file located unter `%appdata%\NEAV1E\Queue`:
```json
"UniqueIdentifier": "DcwTruXZzWsTJRx",
````

The idea was that people may want to encode the same video with different presets. To avoid conflicts a random identifier is created.

So far the program, even with v2.x.x, automatically resumed the encoding process, however the "status" of the encoded files wasn't saved/loaded, which only had affects on the UI Progressbar and status message. In other words: It is resuming properly, but just wasn't displayed. 

With this commit: https://github.com/Alkl58/NotEnoughAV1Encodes/commit/4b80ef800b4e236add3f3b38c30f075f03959c8c the behavior is now changed and should now properly show the status of the encode.

> export/import of the list also can be a great addition.

The queue items are stored under `%appdata%\NEAV1E\Queue`. Exporting the list would literally just copy this folders contents, so I don't know if this would be a worthy option to implement - or adding a button to open this folder? I honestly don't know.

____
Apart from that, I will be less active for the next 1 - 2 weeks because of University exams.

**Comment by Palulukas** [comment]
Hello Alkl58, 

I understand your points here but with the latest 2.0.6 I find it hard to understand which items in queue I edit and which not. 
Your project is incredibly good so far but being able to edit multiple files in queue for language, subtitles and audio would be a much appreciated feature! :-)
For a not tech-skilled user it is hard to change the language or subtitles for multiple files in queue. At the moment you have to edit every file at once which is frustrating for a 200+ file project like I had last week. 
Am I the only one struggling in those situations?

**Comment by Alkl58** [comment]
> Your project is incredibly good so far but being able to edit multiple files in queue for language, subtitles and audio would be a much appreciated feature! :-)

I am currently thinking about how the implementation should work... Should the user be able to select the track number of which the things should be changed? Generally NEAV1E reads the language and title from audio and subtitle from the input file, so it all would be overridden in such a feature.

I would appreciate if you could describe more how exactly you think it should work, so that I have a better idea what to do :)

**Comment by Alkl58** [comment]
Closing, as pretty much all feature requests from this issue are implemented.

**Comment by neoOpus** [comment]
> Closing, as pretty much all feature requests from this issue are implemented.

Thank you so much for your hard work. I'm really pleased with the stability of the new releases and the useful features they bring. SVT-AV1 is a real game-changer; it's enabled me to encode video tutorials like crazy over the last few weeks. Not only have I been able to do this quickly, but I've been able to do it with very minimal effort.  
  
If you are open to a new set of suggestions, ideas then let me know as I would rather not sound demanding.
